### ISSUE TITLE
Filter is empty

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/landscape#37]
The filter box appears empty but It would be great to enable it and show at least the basic information available in the landscape like text search, category and subcategory.

**Comment by DarhkVoyd** [comment]
I am working on this issue. Thank you

**Comment by benjagm** [comment]
@DarhkVoyd What is the status of this?

**Comment by DarhkVoyd** [comment]
There's a bug in the current release of the landscape tool causing default filters not to display. It's unclear yet if this bug affects external API-based filters (since they haven't been integrated).
Building the tool from the latest GitHub source confirms the filters work properly. We'll update once a new release is available.

**Comment by benjagm** [comment]
Now this is working.
